<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>fileTypes</key>
		<array>
			<string>aql</string>
		</array>
		<key>foldingStartMarker</key>
		<string>\s*\(\s*$</string>
		<key>foldingStopMarker</key>
		<string>^\s*\)</string>
		<key>name</key>
		<string>Aql (Arango Query Language)</string>
		<key>patterns</key>
		<array>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>\b(for|in|let|filter|sort|return|update|with|insert|remove|collect|limit|asc|desc|into|not|and|or|null|true|false|FOR|IN|LET|FILTER|SORT|RETURN|UPDATE|WITH|INSERT|REMOVE|COLLECT|LIMIT|ASC|DESC|INTO|NOT|AND|OR|NULL|TRUE|FALSE)\b</string>
						<key>name</key>
						<string>storage.modifier.aql</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>\b(to_bool|to_number|to_string|to_list|is_null|is_bool|is_number|is_string|is_list|is_document|TO_BOOL|TO_NUMBER|TO_STRING|TO_LIST|IS_NULL|IS_BOOL|IS_NUMBER|IS_STRING|IS_LIST|IS_DOCUMENT)\b</string>
						<key>name</key>
						<string>entity.name.function.aql</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>\b(concat|concat_separator|char_length|lower|upper|substitute|substring|left|right|trim|ltrim|rtrim|split|reverse|contains|find_first|find_last|like|CONCAT|CONCAT_SEPARATOR|CHAR_LENGTH|LOWER|UPPER|SUBSTITUTE|SUBSTRING|LEFT|RIGHT|TRIM|LTRIM|RTRIM|SPLIT|REVERSE|CONTAINS|FIND_FIRST|FIND_LAST|LIKE)\b</string>
						<key>name</key>
						<string>entity.name.function.aql</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>\b(floor|ceil|round|abs|sqrt|rand|FLOOR|CEIL|ROUND|ABS|SQRT|RAND)\b</string>
						<key>name</key>
						<string>entity.name.function.aql</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>\b(date_timestamp|date_iso8601|date_dayofweek|date_year|date_month|date_day|date_hour|date_minute|date_second|date_millisecond|date_now|DATE_TIMESTAMP|DATE_ISO8601|DATE_DAYOFWEEK|DATE_YEAR|DATE_MONTH|DATE_DAY|DATE_HOUR|DATE_MINUTE|DATE_SECOND|DATE_MILLISECOND|DATE_NOW)\b</string>
						<key>name</key>
						<string>entity.name.function.aql</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>\b(length|flatten|min|max|average|sum|median|percentile|variance_population|variance_sample|stddev_population|stddev_sample|reverse|first|last|nth|position|slice|unique|union|union_distinct|minus|intersection|LENGTH|FLATTEN|MIN|MAX|AVERAGE|SUM|MEDIAN|PERCENTILE|VARIANCE_POPULATION|VARIANCE_SAMPLE|STDDEV_POPULATION|STDDEV_SAMPLE|REVERSE|FIRST|LAST|NTH|POSITION|SLICE|UNIQUE|UNION|UNION_DISTINCT|MINUS|INTERSECTION|append|push|unshift|pop|shift|remove_value|remove_values|remove_nth|APPEND|PUSH|UNSHIFT|POP|SHIFT|REMOVE_VALUE|REMOVE_VALUES|REMOVE_NTH)\b</string>
						<key>name</key>
						<string>entity.name.function.aql</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>\b(matches|merge|merge_recursive|translate|has|attributes|values|zip|unset|keep|parse_identifier|MATCHES|MERGE|MERGE_RECURSIVE|TRANSLATE|HAS|ATTRIBUTES|VALUES|ZIP|UNSET|KEEP|PARSE_IDENTIFIER)\b</string>
						<key>name</key>
						<string>entity.name.function.aql</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>\b(near|within|within_rectangle|is_in_polygon|NEAR|WITHIN|WITHIN_RECTANGLE|IS_IN_POLYGON)\b</string>
						<key>name</key>
						<string>entity.name.function.aql</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>\b(fulltext|FULLTEXT)\b</string>
						<key>name</key>
						<string>entity.name.function.aql</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>\b(paths|traversal|traversal_tree|shortest_path|neighbors|PATHS|TRAVERSAL|TRAVERSAL_TREE|SHORTEST_PATH|NEIGHBORS)\b</string>
						<key>name</key>
						<string>entity.name.function.aql</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>match</key>
						<string>\b(not_null|first_list|first_document|collections|current_user|document|skiplist|not_null|FIRST_LIST|FIRST_DOCUMENT|COLLECTIONS|CURRENT_USER|DOCUMENT|SKIPLIST|call|apply|CALL|APPLY)\b</string>
						<key>name</key>
						<string>entity.name.function.aql</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>begin</key>
				<string>/\*</string>
				<key>captures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.comment.aql</string>
					</dict>
				</dict>
				<key>end</key>
				<string>\*/</string>
				<key>name</key>
				<string>comment.block.aql</string>
			</dict>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.comment.aql</string>
					</dict>
				</dict>
				<key>match</key>
				<string>(//).*$\n?</string>
				<key>name</key>
				<string>comment.line.double-slash.aql</string>
			</dict>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.string.aql</string>
					</dict>
				</dict>
				<key>match</key>
				<string>".*"</string>
				<key>name</key>
				<string>string.line.quote.aql</string>
			</dict>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.string.aql</string>
					</dict>
				</dict>
				<key>match</key>
				<string>'.*'</string>
				<key>name</key>
				<string>string.line.singlequote.aql</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\b(instanceof)\b</string>
				<key>name</key>
				<string>keyword.operator.aql</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)\b</string>
				<key>name</key>
				<string>constant.numeric.aql</string>
			</dict>
		</array>
		<key>scopeName</key>
		<string>source.aql</string>
		<key>uuid</key>
		<string>2d3d6640-a64c-4466-8d89-9de2080db89a</string>
	</dict>
</plist>